[0.000000] (-) TimerEvent: {}
[0.000812] (new_sensor) JobQueued: {'identifier': 'new_sensor', 'dependencies': OrderedDict()}
[0.000889] (new_sensor) JobStarted: {'identifier': 'new_sensor'}
[0.099680] (-) TimerEvent: {}
[0.200086] (-) TimerEvent: {}
[0.300415] (-) TimerEvent: {}
[0.400726] (-) TimerEvent: {}
[0.501115] (-) TimerEvent: {}
[0.601628] (-) TimerEvent: {}
[0.701954] (-) TimerEvent: {}
[0.802295] (-) TimerEvent: {}
[0.902606] (-) TimerEvent: {}
[1.002969] (-) TimerEvent: {}
[1.070407] (new_sensor) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 85, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 175, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/home/ubuntu/ros2_ws/src/new_sensor/setup.py", line 5, in <module>\n    setup(\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup\n    return distutils.core.setup(**attrs)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 171, in setup\n    ok = dist.parse_command_line()\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 473, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/dist.py", line 952, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 688, in handle_display_options\n    self.print_commands()\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/dist.py", line 731, in print_commands\n    cmdclass = ep.load()\n  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load\n    module = import_module(match.group(\'module\'))\n  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 7, in <module>\n    from setuptools.command.easy_install import easy_install\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 51, in <module>\n    from setuptools.sandbox import run_setup\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/sandbox.py", line 15, in <module>\n    import pkg_resources\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3480, in <module>\n    def _initialize_master_working_set():\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3463, in _call_aside\n    f(*args, **kwargs)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3492, in _initialize_master_working_set\n    working_set = _declare_state(\'object\', \'working_set\', WorkingSet._build_master())\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 619, in _build_master\n    ws = cls()\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 612, in __init__\n    self.add_entry(entry)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 668, in add_entry\n    for dist in find_distributions(entry, True):\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2182, in find_on_path\n    yield from factory(fullpath)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2246, in distributions_from_metadata\n    yield Distribution.from_location(\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2773, in from_location\n    return cls(\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2748, in __init__\n    self._version = safe_version(version)\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1428, in safe_version\n    return str(_packaging_version.Version(version))\n  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 198, in __init__\n    match = self._regex.search(version)\nKeyboardInterrupt\n\n'}
[1.070976] (new_sensor) JobEnded: {'identifier': 'new_sensor', 'rc': 'SIGINT'}
[1.080800] (-) EventReactorShutdown: {}
