[1.070s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 85, in build
    available_commands = await self._get_available_commands(
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 175, in _get_available_commands
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/python3', 'setup.py', '--help-commands'] to pass: Traceback (most recent call last):
  File "/home/ubuntu/ros2_ws/src/new_sensor/setup.py", line 5, in <module>
    setup(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 171, in setup
    ok = dist.parse_command_line()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 473, in parse_command_line
    if self.handle_display_options(option_order):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/dist.py", line 952, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 688, in handle_display_options
    self.print_commands()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/dist.py", line 731, in print_commands
    cmdclass = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 7, in <module>
    from setuptools.command.easy_install import easy_install
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 51, in <module>
    from setuptools.sandbox import run_setup
  File "/home/ubuntu/.local/lib/python3.10/site-packages/setuptools/sandbox.py", line 15, in <module>
    import pkg_resources
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3480, in <module>
    def _initialize_master_working_set():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3463, in _call_aside
    f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3492, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 619, in _build_master
    ws = cls()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 612, in __init__
    self.add_entry(entry)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 668, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2182, in find_on_path
    yield from factory(fullpath)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2246, in distributions_from_metadata
    yield Distribution.from_location(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2773, in from_location
    return cls(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2748, in __init__
    self._version = safe_version(version)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1428, in safe_version
    return str(_packaging_version.Version(version))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 198, in __init__
    match = self._regex.search(version)
KeyboardInterrupt

